name: 'dbt_click'
version: 1.0.0
config-version: 2

profile: 'dbt_click'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"  
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_click:
    operations:
      +materialized: view
